from fuzzy_implication.fuzzy_implication import FuzzyImplication
from fuzzy_implication.godel_implication_solver import GodelImplicationSolver
from fuzzy_implication.weber_implication_solver import WeberImplicationSolver