from fuzzy_inference_tests.test_fuzzy_set_parser import FuzzySetParserTests
from fuzzy_inference_tests.test_implication_parser import FuzzyImplicationParserTests
from fuzzy_inference_tests.test_inference_input import InferenceInputTests
from fuzzy_inference_tests.test_godel_implication import TestGodelImplicationSolver
from fuzzy_inference_tests.test_weber_implication import TestWeberImplicationSolver
from fuzzy_inference_tests.test_min_tnorm import TestMinTNorm
from fuzzy_inference_tests.test_drastic_product import TestDrasticProduct